Skip java stuff in bashrc for OSX

diff --git a/osx-dotfiles/bashrc b/osx-dotfiles/bashrc
--- a/osx-dotfiles/bashrc
+++ b/osx-dotfiles/bashrc
@@ -34,7 +34,7 @@ function setjdk() {
 function removeFromPath() {
   export PATH=$(echo $PATH | sed -E -e "s;:$1;;" -e "s;$1:?;;")
 }
-setjdk 1.8 || echo "ERROR: JDK could not be set!"
+# setjdk 1.8 || echo "ERROR: JDK could not be set!"
 
 
 export PATH="$PATH:$HOME/.cabal/bin"
